import {
  ApplicationConfig,
  provideZoneChangeDetection,
  provideAppInitializer,
  inject,
} from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { en_US, provideNzI18n } from 'ng-zorro-antd/i18n';
import { provideNzIcons } from 'ng-zorro-antd/icon';
import {
  ApartmentOutline,
  CalendarOutline,
  CaretDownOutline,
  CaretUpOutline,
  CheckCircleOutline,
  CloseCircleFill,
  CloseOutline,
  DeleteOutline,
  DoubleLeftOutline,
  DoubleRightOutline,
  DownOutline,
  DownloadOutline,
  EditOutline,
  EyeOutline,
  FileExcelOutline,
  FilterOutline,
  FolderOutline,
  HistoryOutline,
  HomeOutline,
  KeyOutline,
  LeftOutline,
  LoadingOutline,
  LockOutline,
  MoreOutline,
  OrderedListOutline,
  PlusOutline,
  ReloadOutline,
  RightOutline,
  SafetyCertificateOutline,
  SaveOutline,
  SearchOutline,
  SettingOutline,
  SwapOutline,
  SyncOutline,
  TeamOutline,
  ThunderboltOutline,
  UnlockOutline,
  UploadOutline,
  UserAddOutline,
  UserDeleteOutline,
  BellOutline,
  EyeInvisibleOutline,
  EllipsisOutline,
  FolderOpenOutline,
  LogoutOutline,
  MenuOutline,
  QuestionCircleOutline,
  UserOutline,
  LeftCircleOutline,
  RightCircleOutline,
} from '@ant-design/icons-angular/icons';

import { authInterceptor, AUTH_CONFIG, AuthService } from '@platform/shared';
import { SS_ERROR_MESSAGES, SS_DEFAULT_ERROR_MESSAGES } from '@platform/ui-kit';
import { environment } from '@env/environment';
import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes, withComponentInputBinding()),
    provideHttpClient(withInterceptors([authInterceptor])),
    provideAnimationsAsync(),
    provideNzI18n(en_US),
    provideNzIcons([
      ApartmentOutline,
      CalendarOutline,
      CaretDownOutline,
      CaretUpOutline,
      CheckCircleOutline,
      CloseCircleFill,
      CloseOutline,
      DeleteOutline,
      DoubleLeftOutline,
      DoubleRightOutline,
      DownOutline,
      DownloadOutline,
      EditOutline,
      EyeOutline,
      FileExcelOutline,
      FilterOutline,
      FolderOutline,
      HistoryOutline,
      HomeOutline,
      KeyOutline,
      LeftOutline,
      LoadingOutline,
      LockOutline,
      MoreOutline,
      OrderedListOutline,
      PlusOutline,
      ReloadOutline,
      RightOutline,
      SafetyCertificateOutline,
      SaveOutline,
      SearchOutline,
      SettingOutline,
      SwapOutline,
      SyncOutline,
      TeamOutline,
      ThunderboltOutline,
      UnlockOutline,
      UploadOutline,
      UserAddOutline,
      UserDeleteOutline,
      BellOutline,
      EyeInvisibleOutline,
      EllipsisOutline,
      FolderOpenOutline,
      LogoutOutline,
      MenuOutline,
      QuestionCircleOutline,
      UserOutline,
      LeftCircleOutline,
      RightCircleOutline,
    ]),
    provideAppInitializer(async () => {
      const auth = inject(AuthService);
      try {
        await auth.init();
      } catch (e) {
        console.error('[AppInit] Auth init failed:', e);
      }
    }),
    {
      provide: AUTH_CONFIG,
      useValue: environment.auth,
    },
    {
      provide: SS_ERROR_MESSAGES,
      useValue: SS_DEFAULT_ERROR_MESSAGES,
    },
  ],
};
